Делает разметку главной страницы
htmlacademy-adaptive/142152-pink-24 pull request #2
Opened 2021-11-28 09:39 UTC by DaryaNikolaeva31

2021-11-28 19:15 UTC, wrgraff requested changes
Уфф, понаписал.
Кажется, с БЭМом пока не все просто. Давай наверное отправим тебя посмотреть на [пошаговую разметку формы](https://youtube.com/playlist?list=PL6xpnt2woRKk0btmfzM2oR6-ste7wZUWm). Формы — сложные части страниц, я там попытался подробно расписывать что и зачем делаю.

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +    <div class="price">
Почему выбор в пользу дива?
Разве таблица с прайсом — не полноценный логический блок?

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +      <table>
Я бы добавил разделение на `<thead>` и `<tbody>`

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +          <th>База 1,99 USD</th>
А как ты оформишь по разному этот текст, не выделив никакими тегами и классами?

Выглядят они не одинаково:
![изображение](https://user-images.githubusercontent.com/37917037/143782175-442c971c-4323-42e8-abd3-f1cc13fe97cf.png)

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +          <td></td>
Каково содержимое ячеек будет?
Как понять инструментами доступности, что именно в тариф включено, а что нет?

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +        </tr>
Вообще в таблице классов маловато, как оформлять то ее )

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +          <p class="text-box__description text-box__description--contacts">+7 (812) 555-66-66</p>
Кажется, эти красные тексты — это ссылки =)

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +              viewBox="0 0 18 14" fill="none">
Целых 5 БЭМ-блоков на список соцсетей 😲
Хватило бы на 4 меньше!

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +            <svg class="footer-social-icon" aria-hidden="true" focusable="false" width="9" height="18"
А точно ли эта иконка нужна в разметке?

То, что ты добавляешь скрытую подпись `<span class="visually-hidden">Facebook</span>` уже говорит о том, что иконки у нас больше декоративные.
Помнишь, зачем они вставляются в разметку? Чтобы менять им цвет.
Нужно ли им менять цвет или же этого эффекта можно добиться цветом рамки, прозрачностью и псевдоэлементом?
![изображение](https://user-images.githubusercontent.com/37917037/143782467-ec1347f6-3ff6-484e-a006-f3051fbc5115.png)

2021-11-28 19:15 UTC, wrgraff commented on source/index.html
> +      </a>
Пустая ссылка?

2021-11-28 19:34 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <img class="logo" src="img/pink.svg" width="74" height="23" alt="Логотип сайта Пинк.">
На Лайве они специально убрали класс с логотипа и сказали "мы объясним вам потом для чего"

2021-11-28 19:35 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <a href="index.html">
Я смотрела макет, там не было активного пункта меню
С другой стороны, это не значит, что завтра он не появится)верно?)

2021-11-28 19:50 UTC, wrgraff commented on source/index.html
> +      <img class="logo" src="img/pink.svg" width="74" height="23" alt="Логотип сайта Пинк.">
Обожаю этот стиль "делайте так, просто потому что мы сказали".
Но тут то класс не убран. И я не предлагаю ничего добавить, а переместить наш блок на уровень ссылки с уровня картинки

2021-11-28 20:23 UTC, wrgraff commented on source/index.html
> +          <a href="index.html">
Он почему-то есть на страницах (кроме главной).
Задумка это или баг?..

2021-11-29 10:19 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <img class="logo" src="img/pink.svg" width="74" height="23" alt="Логотип сайта Пинк.">
добавила на ссылку класс logo-теперь ссылка не только элемент блока page-header, но и сама блок logo

2021-11-29 10:21 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <button class="button__close" type="button">
тогда я удаляю кнопку close. 
то есть мы при состоянии нажатия будем подставлять вместо иконки меню-крестик?
и при нажатии еще должен раскрываться список меню

2021-11-29 10:22 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <button class="button__close" type="button">
удалила эту кнопку

2021-11-29 10:26 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <a href="#">
catalog.html 
contest.html 
добавила

2021-11-29 10:35 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <a href="index.html">
добавила ссылке класс class="main-nav__link"
добавила элементу списка дополнительный класс с модификатором main-nav__item--current
еще исправила блок и названия элементов этого блока навигации

2021-11-29 10:37 UTC, wrgraff commented on source/index.html
> +      <button class="button__close" type="button">
Да, все так и будет работать

2021-11-29 10:37 UTC, wrgraff commented on source/index.html
> +          <a href="#">
Используй `form.html`

2021-11-29 10:37 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <img src="img/phone.jpg" width="320" height="462" alt="Реклама приложения.">
у меня тоже не возникает понимания, когда я смотрю на макет)
заменила...

2021-11-29 16:22 UTC, DaryaNikolaeva31 commented on source/index.html
> +    <p class="motivation__text motivation__text--slogan">Взгляните на жизнь иначе!</p>
я немного все переделала)

2021-11-29 16:23 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <a href="#">
не очень понимаю, как form связано со страницей конкурс, но поменяю

2021-11-29 16:24 UTC, DaryaNikolaeva31 commented on source/index.html
> +    <a class="dowload-apps__button" href="#">
поменяла немного блоки

2021-11-29 16:26 UTC, DaryaNikolaeva31 commented on source/index.html
> +            <svg class="downloading-icon" aria-hidden="true" focusable="false" width="47" height="56"
заменила

2021-11-29 16:27 UTC, DaryaNikolaeva31 commented on source/index.html
> +            </svg>
та же ошибка что и на первом курсе, мне показалось, что они светлеют, значит меняют свое состояние
но теперь я вспомнила, сейчас удалю иконки

2021-11-29 19:15 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <a class="fdownloading__link" href="#">
поправила, проверила-дерево ошибок не выдает-технических)

2021-11-29 19:19 UTC, DaryaNikolaeva31 commented on source/index.html
> +    <p class="motivation__text motivation__text--motto">Устали от серости мегаполиса? Нам есть, что вам предложить!</p>
переделала, трижды по-моему)

2021-11-29 19:21 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <p class="text-box__description text-box__description--advantages">Приложение позволит вам победить осеннюю
сделала блок преимуществ отдельным блоком

2021-11-29 19:31 UTC, DaryaNikolaeva31 commented on source/index.html
> +    </div>
это картинка относится к преимуществам
добавила в этот section
убрала див
класс добавила к img и заменила на smile

2021-11-29 19:40 UTC, DaryaNikolaeva31 commented on source/index.html
> +    <div class="information">
переделала)

2021-11-29 19:40 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <svg aria-hidden="true" focusable="false" width="238" height="276" viewBox="0 0 238 276" fill="none">
да лошара я
подумала что раз она svg то тут таже схема что и с логотипом
удалила!

2021-11-29 19:41 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="reviews-item">
изначально так и было!)
переделала

2021-11-29 19:41 UTC, DaryaNikolaeva31 commented on source/index.html
> +    <div class="price">
поменяла на section

2021-11-29 19:50 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <table>
я очень плохо знакома с таблицами и с тегами(хуже, чем со всем остальным))
добавила, но не уверена, что правильно
в тренажерах такого не помню, в интернете примеров маловато, в дискорде у меня нет чата адаптива(решила пока не писать модератору об этой проблеме)-ничего хорошего он мне не принес в прошлый раз)

2021-11-29 19:52 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <th>База 1,99 USD</th>
на первый взгляд, кажется, что они отличаются только жирностью?
для этого нужны именно разные классы для каждого? или я могу первый просто выделить тегом b?

2021-11-29 20:01 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <td></td>
вероятно ты это подразумевал под инструментами доступности?

ты возможно спросишь, зачем оба класса? мне кажется стоит отметить два, но я не могу объяснить почему)

2021-11-29 20:07 UTC, DaryaNikolaeva31 commented on source/index.html
> +        </tr>
добавила немного

2021-11-29 20:23 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <p class="text-box__description text-box__description--contacts">+7 (812) 555-66-66</p>
сделала

2021-11-29 20:23 UTC, DaryaNikolaeva31 commented on source/index.html
> +              viewBox="0 0 18 14" fill="none">
исправила

2021-11-29 20:24 UTC, DaryaNikolaeva31 commented on source/index.html
> +            <svg class="footer-social-icon" aria-hidden="true" focusable="false" width="9" height="18"
удалила(

2021-11-29 20:30 UTC, DaryaNikolaeva31 commented on source/index.html
> +      </a>
исправила

2021-11-30 07:40 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="advantages-item">
Поправила

2021-11-30 17:15 UTC, wrgraff commented on source/index.html
> +          <a href="#">
Форма заявки на конкурс )
Обрати внимание на то, как она называется [в ТЗ](https://up.htmlacademy.ru/adaptive/24/project/pink#pink-5-1)

2021-11-30 17:19 UTC, wrgraff commented on source/index.html
> +        alt="Взгляните на мир в розовых красках.">
Описание понятнее не стало )
Оно должно дать описание тому, кто картинку не видит. Типа, что мы видим? Телефон в руке с запущенным приложением.
Либо, если это не существенная картинка, убрать ее из разметки вовсе. Обычно если нормальное описание получается — это повод из разметки убрать картинку

2021-11-30 17:19 UTC, wrgraff commented on source/index.html
> +    <a class="dowload-apps__button" href="#">
_Немного_, ага )

2021-11-30 17:24 UTC, wrgraff commented on source/index.html
> +            </svg>
Их же вообще нет в стайлгайде

2021-11-30 17:25 UTC, wrgraff commented on source/index.html
> +          <a class="fdownloading__link" href="#">
И правда не выдает

2021-11-30 17:33 UTC, wrgraff commented on source/index.html
> +      <img class="smile" src="img/phone-smile.jpg" width="157" height="320" alt="Пример использования приложения.">
А как потом этак картинка превратится в 3 картинки? =)
Лучше через стили )

2021-11-30 17:33 UTC, wrgraff commented on source/index.html
> +          <th>База 1,99 USD</th>
Да нет, у них размер шрифта тоже разный.
16 и 18

2021-11-30 17:34 UTC, wrgraff commented on source/index.html
> +          <td></td>
Под доступностью я имею ввиду доступность =)
Типа, как будут это читать скринридеры, которыми пользуются незрячие люди.
Имена классов скринридеры читать не будут :(

2021-11-30 17:56 UTC, wrgraff approved these changes
Жду поправленную табличку в следующем задании =)

2021-11-30 17:56 UTC, wrgraff commented on source/index.html
> +      <p class="subtitle subtitle--download">Доступно для iPhone, iPad, Android, Windows
Я бы наверное сделал это частью блока `download`. Не вижу где этот текст прям переиспользуется

2021-11-30 17:56 UTC, wrgraff commented on source/index.html
> +        </tbody>
Смысл `<tbody>` в том, что он оборачивает тело таблицы.
У тебя он оборачивает каждую строку. Это неправильно, он должен объединить все строки под заголовочными ячейками с названиями тарифов

2021-11-30 17:56 UTC, wrgraff commented on source/index.html
> +            <td class="included"></td>
Получается, в таблице нет ни одного элемента... По сути, она не размечена по БЭМ =(

<details>
  <summary>У меня есть пример разметки:</summary>

```html
  <table class="prices">
      <thead class="prices__head">
          <tr>
              <th></th>
              <th class="prices__heading">
                  База<br>
                  <small>1,99 USD</small>
              </th>
              <th class="prices__heading prices__heading--hit">
                  Стандарт<br>
                  <small>3,99 USD</small>
              </th>
              <th class="prices__heading">
                  Анлим<br>
                  <small>9,99 USD</small>
              </th>
          </tr>
      </thead>

      <tbody class="prices__body">
          <tr>
              <th class="prices__item prices__item--title">Розовый фильтр</th>
              <td class="prices__item prices__item--true"></td>
              <td class="prices__item prices__item--true"></td>
              <td class="prices__item prices__item--true"></td>
          </tr>
          <tr>
              <th class="prices__item prices__item--title">Смайлики</th>
              <td class="prices__item prices__item--false"></td>
              <td class="prices__item prices__item--true"></td>
              <td class="prices__item prices__item--true"></td>
          </tr>
          <tr>
              <th class="prices__item prices__item--title">Комментарии</th>
              <td class="prices__item prices__item--false"></td>
              <td class="prices__item prices__item--false"></td>
              <td class="prices__item prices__item--true"></td>
          </tr>
      </tbody>
  </table>
```

</details>

Копировать его не стоит, пожалуй, так как разметка в нем очень уж лайтовая. Я ее делал для другой демки: тут самый минимум, не все элементы в наличии и даже не учтена доступность.
Но направление мысли должно задать.

2021-11-30 17:56 UTC, wrgraff commented on source/index.html
> +            <td class="excluded"></td>
Должен быть какой-то текстовый контент, скрытый визуально

2021-11-30 17:56 UTC, wrgraff commented on source/index.html
> +            <td class="included"></td>
Я бы подумал в сторону одного элемента с разными модификаторами

2021-11-30 17:56 UTC, merged

2021-11-30 19:21 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <p class="subtitle subtitle--download">Доступно для iPhone, iPad, Android, Windows
исправила!

2021-11-30 19:22 UTC, DaryaNikolaeva31 commented on source/index.html
> +      <img class="smile" src="img/phone-smile.jpg" width="157" height="320" alt="Пример использования приложения.">
убрала ее)

2021-11-30 19:23 UTC, DaryaNikolaeva31 commented on source/index.html
> +        alt="Взгляните на мир в розовых красках.">
убрала картинку

2021-11-30 19:36 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <th>База 1,99 USD</th>
добавила им p и span с классами

2021-11-30 19:40 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <td></td>
добавила span class="visually-hidden"

2021-11-30 20:23 UTC, DaryaNikolaeva31 commented on source/index.html
> +            <td class="included"></td>
постаралась поправить!

2021-11-30 20:24 UTC, DaryaNikolaeva31 commented on source/index.html
> +            <td class="excluded"></td>
добавила
лажанула-это же как со звездами в седоне!)

2021-11-30 20:24 UTC, DaryaNikolaeva31 commented on source/index.html
> +            <td class="included"></td>
дада,добавила!