Разметка внутренних страниц
htmlacademy-adaptive/142152-pink-24 pull request #3
Opened 2021-12-02 20:31 UTC by DaryaNikolaeva31

2021-12-02 22:41 UTC, wrgraff requested changes

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +        <li class="main-nav__item main-nav__item--current">
Кажется, не главная страница тут активная

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +    <h1 class="title title--catalog">Фотографии
А в чем отличие этого заголовка от прочих?
Почему такой модификатор?
Не то чтобы это неправильно, но мне просто интересно

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +        <li class="product-card">
А ты прям лишние элементы не хочешь создавать?
Ошибки тут нет, конечно, но интересно, почему не отметить, что это элементы блока `product-list`.

Я смотрю, миксования очень мало у тебя. Ты его не боишься случаем?

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +          <h3 class="visually-hidden">Имя пользователя и время публикации</h3>
Но так может показаться, что вся карточка — это только имя и время. А что тут еще и картинка нигде не говорится...

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +        <li class="product-card">
Почему этот блок называется `product-card`?
Не очень похоже на продукт... Это ж фото.

В других местах тоже продукт упоминается

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +      <form class="post__form form" action="https://echo.htmlacademy.ru/" method="get">
`form` очень уж общий класс. Это может быть любой формой вообще. А тут то как раз довольно специфическая форма

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +      <form class="post__form form" action="https://echo.htmlacademy.ru/" method="get">
Почему GET? Мы вроде бы только отправить данные планируем, нам результат затем не требуется

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +          <legend class="visually-hidden">Выберите фото для поста</legend>
Выбор фото относился бы к инпуту, который подключал бы картинку. А это у тебя группа полей с редактированием картинки

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +          <ul class="form-list">
Опять же, очень общий блок. "Список формы" — слишком общее для такого специфического по виду блока

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +                  <span class="visually-hidden">Выберите степень кадрирования изображения.</span>
Этак кнопка (как и другие) не выбирает степень кадрирования. Она выбирает активный инпут, и уже инпут будет выбирать степень.

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +            <li class="form-list__item">
Я бы подумал, стоит ли тут именно список делать. Это скорее набор вкладок. Кажется, список тут несколько излишен

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +              <div class="form-list__field">
А зачем еще одна обертка?

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +                </label>
Инпут оказался без подписи.
То есть, он обернут в лейбл, но текста никакого в нем нет внутри, а значит и подписи нет

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +                <label class="form-list__scale form-list__scale--fill">
Зачем модификатор кнопке — понятно.
А зачем он инпуту? Они все выглядят одинаково, вне зависимости от того, чем управляют

2021-12-02 22:41 UTC, wrgraff commented on source/catalog.html
> +      </form>
Ошибка форматирования =(

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +        <li class="main-nav__item main-nav__item--current">
Это тоже не главная.
Эх... Копировать код надо с учетом изменений! =)

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +              </div>
Погоди, а как это попап оказался посреди списка?
По место в макете что ли? Так он ведь ставится поверх страницы через `position: fixed;`

Вообще, они всегда располагаются в самом низу кода, потому что по умолчанию скрыты и браузеру важнее распарсить весь контент до формы, так как он сразу же открыт.

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +                <button class="popup__button button" type="submit">
Тип `submit` — это для формы.

Зачем м вообще прописываем типы кнопкам?
По умолчанию кнопки работают как отправка формы. И если случайно из-за глюка в коде с незакрытым тегом формы наша кнопка отправит данные вместо переключения слайдера, то будет не здорово 🙃

Поэтому, таким кнопкам обязательно надо прописать `type="button"`.

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +              <div class="popup popup-failed">
Это не попап, а модалка.
Попап не блокирует работу с сайтом.
Вот у меня прямо в интерфейсе ревью есть попап: 
![изображение](https://user-images.githubusercontent.com/37917037/144514181-6bcb1a67-10ba-4488-aecc-69246ef4fb4f.png)

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +        </div>
Тут все аналогично первому окошку

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +            </li>
А где список закрывается?

2021-12-02 22:41 UTC, wrgraff commented on source/form.html
> +        </button>
Разметку конечно мою повторила хорошо xD
Надеюсь, что-то и усвоилось тоже =)

2021-12-02 22:41 UTC, wrgraff commented on source/index.html
> +              <span class="visually-hidden">Эта опция включена в тариф "База" 1,99 USD</span>
Это немного оверкилл. Инструмент доступности должен и так предоставить информацию о том, что это за ряд и какая колонка. Достаточно просто указать, что опция включена (хотя, если посмотреть на ячейки на разных разрешениях, то будет видно, что надпись то в первой колонке, то внутри. Но это решается по разному и можно отложить на момент, когда ты уже будешь иметь представление о том, как работают медиа-запросы)

2021-12-03 09:51 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        <li class="main-nav__item main-nav__item--current">
замменила

2021-12-03 09:52 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +    <h1 class="title title--catalog">Фотографии
убрала модификатор, оставила только блок

2021-12-03 09:54 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        <li class="product-card">
боюсь)я всего боюсь)
файл комитить боюсь
про миксование вообще молчу)

сделала элементы блока product-list

2021-12-03 09:57 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        <li class="product-card">
миксование это же вот так?
<li class="product-list__card product-card">

2021-12-03 10:15 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <h3 class="visually-hidden">Имя пользователя и время публикации</h3>
заменила на "пост"

2021-12-03 10:21 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +      <form class="post__form form" action="https://echo.htmlacademy.ru/" method="get">
метод post тогда лучше выбрать?

2021-12-03 10:22 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +      <form class="post__form form" action="https://echo.htmlacademy.ru/" method="get">
заменила на post

2021-12-03 10:30 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +      <form class="post__form form" action="https://echo.htmlacademy.ru/" method="get">
заменила на photo-post

2021-12-03 10:36 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <ul class="form-list">
заменила на photo-post

2021-12-03 10:52 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        <li class="product-card">
заменила на photo-card

2021-12-03 11:01 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                  <span class="visually-hidden">Выберите степень кадрирования изображения.</span>
переместила внутрь label после input

2021-12-03 11:05 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <legend class="visually-hidden">Выберите фото для поста</legend>
убрала fieldset и legend

2021-12-03 11:16 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +              <div class="form-list__field">
честно говоря, уже не помню)но для чего-то добавила
убрала

2021-12-03 11:17 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                </label>
я переместила спан после инпута со скрытым текстом, это подойдет? или лучше перед инпутом?

2021-12-03 11:19 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                <label class="form-list__scale form-list__scale--fill">
это я уже перестраховалась)

2021-12-03 11:19 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                <label class="form-list__scale form-list__scale--fill">
удалила

2021-12-03 11:21 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +      </form>
вообще всегда перед отправкой нажимаю отформатировать
может забыла
поправила!

2021-12-03 11:21 UTC, DaryaNikolaeva31 commented on source/form.html
> +        <li class="main-nav__item main-nav__item--current">
поправила

2021-12-03 11:26 UTC, DaryaNikolaeva31 commented on source/form.html
> +              </div>
убрала вниз после footer и перед /body

2021-12-03 11:31 UTC, DaryaNikolaeva31 commented on source/form.html
> +                <button class="popup__button button" type="submit">
заменила

2021-12-03 21:22 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +            <li class="form-list__item">
сделала вкладки, но вообще не уверена, что правильно

2021-12-03 21:23 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                </label>
переделала эту форму
но очень сомневаюсь на ее счет

2021-12-03 21:23 UTC, DaryaNikolaeva31 commented on source/form.html
> +              <div class="popup popup-failed">
заменила классы

2021-12-03 21:23 UTC, DaryaNikolaeva31 commented on source/form.html
> +        </div>
заменила на modal

2021-12-03 21:24 UTC, DaryaNikolaeva31 commented on source/form.html
> +            </li>
ужас 
стыдоба
исправила

2021-12-03 21:27 UTC, DaryaNikolaeva31 commented on source/form.html
> +        </button>
слушай, я каждое твое видео смотрела 4-5 раз
я названиями и воображением у меня туго-поэтому я была рада увидеть адекватные названия и взять их себе
касаемо самих полей и филдсетов-я внимательно следила как ты делал разметку по БЭМ и старалась у себя сделать хорошо
ты же этого добивался?)
я не списала код "под копирку", я его раза два переписывала и, как видишь, в модалках-то ошиблась еще как

2021-12-03 21:28 UTC, DaryaNikolaeva31 commented on source/index.html
> +              <span class="visually-hidden">Эта опция включена в тариф "База" 1,99 USD</span>
исправила на включено/не включено
* думала наоборот для скриридеров - чем больше текста-чем подробнее, тем лучше)

2021-12-04 12:06 UTC, wrgraff commented on source/catalog.html
> +    <h1 class="title title--catalog">Фотографии
Но это же не ответ на вопрос )

2021-12-04 12:06 UTC, wrgraff commented on source/catalog.html
> +        <li class="product-card">
Да, это оно и есть )

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +          <h3 class="visually-hidden">Пост</h3>
Я бы предложил вообще избавиться от заголовков.
Необходимости в них нет здесь, а придумать внятный заголовок сложно. Какая например может быть польза от такой структуры:
- Фотографии пользователей
  - Реальные фото пользователей, использующих приложение
    - Пост
    - Пост
    - Пост
    - Пост
    - Пост

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +        </section>
Смотри, ты поменяла `form` на `photo-post`, но элементы поменялись на `post__*`. То есть, ты их привязала к другому блоку. Кажется, они должны были привязаться к `photo-post`

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +          <button class="tabs__tab" role="tab" aria-selected="true" aria-controls="crop-panel" id="crop-tab"
А где контент у кнопки?

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +          <button class="tabs__tab" role="tab" aria-selected="true" aria-controls="fill-panel" id="fill-tab"
`aria-selected="true"` будет только у активной, к остальных — `aria-selected="false"`
Это атрибут, который сообщает о том, что это не просто кнопка, а кнопка в активном состоянии (по хорошему конечно и пункты меню должны бы так же отмечаться)

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +            tabindex="-1"></button>
`tabindex` им писать не нужно, этими атрибутами управляет JS.

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +        <section class="post__content" role="tabpanel" tabindex="0" aria-labelledby="crop-tab" id="crop-panel">
В примере, что я скинул, используется `<section>` так как там контентные блоки с текстом.
У нас это просто 3 элемента формы. `<section>` для них перебор

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +          </label>
Чтобы сделать `<section>` с заголовком, ты переместила подпись к полю в этот самый заголовок. При этом поле осталось без подписи.

Если ты избавишься от `<section>`, то можно поместить текст в подписи, и проблема будет решена.

2021-12-04 12:24 UTC, wrgraff commented on source/catalog.html
> +            <li class="form-list__item">
Можно было проигнорировать все нюансы реализации и просто сделать кнопки

2021-12-04 12:25 UTC, wrgraff commented on source/catalog.html
> +                </label>
Текст должен быть внутри `<label>`

2021-12-04 12:26 UTC, wrgraff commented on source/catalog.html
> +                <label class="form-list__scale form-list__scale--fill">
Не надо перестраховываться.
Если понадобится модификатор — всегда можно добавить

2021-12-04 12:26 UTC, wrgraff commented on source/catalog.html
> +      </form>
Проблема могла быть в незакрытом теге

2021-12-04 12:30 UTC, wrgraff commented on source/form.html
> +        </button>
В видео довольно устоявшиеся имена классов используются, которые по сути повторяются у многих разработчиков от проекта к проекту.
Так что нового никто не придумывает ничего. Да и не нужно это.

Можно, кстати, и здесь поглядывать в шпаргалку с популярными названиями классов. Использовать их для болоков и в сочетаниях блоков и элементов

2021-12-04 12:32 UTC, wrgraff commented on source/index.html
> +              <span class="visually-hidden">Эта опция включена в тариф "База" 1,99 USD</span>
но у них же есть вся прочая информация в другой части таблицы )

2021-12-04 19:13 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +    <h1 class="title title--catalog">Фотографии
да наверно нет отличия от прочих)

2021-12-04 19:18 UTC, DaryaNikolaeva31 commented on source/form.html
> +        </button>
вообще я туда часто заглядываю, но не нахожу в нужный момент подходящего(

2021-12-04 19:20 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <h3 class="visually-hidden">Пост</h3>
удалила

2021-12-04 19:28 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        </section>
да, но уровнем выше у меня указано было form class="post__form photo-post" 
то есть весь этот большой блок у меня был post и эти элементы я привязывала к нему
что неправильно, я поняла сейчас 
иначе зачем мне делать миксованием photo-post)

2021-12-04 19:33 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <button class="tabs__tab" role="tab" aria-selected="true" aria-controls="crop-panel" id="crop-tab"
добавила span class="visually-hidden"
там же будет иконка и нам надо добавить скрытый текст для скринридеров?

2021-12-04 19:35 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <button class="tabs__tab" role="tab" aria-selected="true" aria-controls="fill-panel" id="fill-tab"
заменила 
у кнопок

2021-12-04 19:36 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +            tabindex="-1"></button>
удалила

2021-12-04 19:42 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        <section class="post__content" role="tabpanel" tabindex="0" aria-labelledby="crop-tab" id="crop-panel">
удалила(

2021-12-04 19:43 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          </label>
я подпись поместила внутрь label

2021-12-04 19:45 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                </label>
сделала внутри label

2021-12-04 19:46 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +                <label class="form-list__scale form-list__scale--fill">
ок

2021-12-04 23:02 UTC, wrgraff commented on source/form.html
> +        </button>
Ну не может же там быть вообще все )

2021-12-04 23:02 UTC, wrgraff commented on source/catalog.html
> +          <button class="tabs__tab" role="tab" aria-selected="true" aria-controls="crop-panel" id="crop-tab"
Да

2021-12-04 23:03 UTC, wrgraff approved these changes

2021-12-04 23:03 UTC, merged