Стилизация всех страниц
htmlacademy-adaptive/142152-pink-24 pull request #4
Opened 2021-12-09 21:00 UTC by DaryaNikolaeva31

главная страница просто кошмар

2021-12-10 18:47 UTC, wrgraff requested changes
Немного перестаралась с попытками попасть в макет.
Можешь на него почти не смотреть даже. Главное, чтобы сборка работала.

2021-12-10 18:47 UTC, wrgraff commented on source/sass/fonts.scss
> +  src: url("/source/fonts/opensans.woff2"), url("/source/fonts/opensans.woff");
Неправильный путь к файлу. Препроцессор не умеет при сборке переписывать пути к файлвм. Это обычная статическая строка. Поэтому нам нужно писать путь исходя из того, где находится наш скомпилированный css-файл.

У нас директория `fonts` находится обычно рядом с директорией `css`, а значит нужно один раз выйти из директории(`../`) и зайти в картинки.

> Почему же при всем при этом шрифты работают?
Потому, что лишние выходы на уровень выше не срабатывают, так как мы сразу попадаем в корневую директорию. Однако, если мы сделаем тоже самое на сервере с другими настройками, то будет проблема. Например, попробуй опубликовать свой пул-реквест в интерфейсе проверки задания (прямо в интерфейсе Академии есть такая кнопка)


https://github.com/htmlacademy-adaptive/142152-pink-24/blob/752df669b801377c49a411d80c68d0a26faf3f44/source/sass/fonts.scss#L13-L14
https://github.com/htmlacademy-adaptive/142152-pink-24/blob/752df669b801377c49a411d80c68d0a26faf3f44/source/sass/fonts.scss#L22-L23

2021-12-10 18:47 UTC, wrgraff commented on source/sass/fonts.scss
> +    url("/source/fonts/opensansbold.woff");
Так симпатичнее.
А еще, нужно единообразно сделать (не важно как — один из твоих вариантов или мой, но надо одинаково).

```suggestion
  src:
    url("/source/fonts/opensansbold.woff2"),
    url("/source/fonts/opensansbold.woff");
```

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/title.scss
> +  text-align: center;
Весь этот набор свойств повторяется.
Так как модификатор без основного класса не применяется, то смысла в этом нет

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/title.scss
> +  padding-bottom: 70px;
Судя по названию модификатора `inverted`, он должен отвечать за цвета.
А здесь еще и отступы меняются. Это неочевидное поведение и это плохо.

И в принципе, расстояния эти вполне можно оставить на блок, в котором будет этот заголовок (а ему придется быть в блоке, потому что что-то должно задать фон)

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
БЭМ-блокам нельзя задавать размеры и внешние отступы.
Основная идея блока в том, что он переиспользуемый, а значит должен подстраиваться под контент в зависимости от контекста.

Например, у нас есть БЭМ-блок `.card` в виде карточки товара. И есть страница с карточками товаров, где в сетке товаров каждая карточка занимает в ширину 320 пикселей.
Мы задаем БЭМ-блоку `.card` ширину 320 пикселей: а что такого?

![https://user-images.githubusercontent.com/37917037/127750217-6f72b53c-d8ce-402b-b342-0cbe69453432.png](https://user-images.githubusercontent.com/37917037/127750217-6f72b53c-d8ce-402b-b342-0cbe69453432.png)

Но на другой странице мы встречаем боковой список товаров, где конечно же будет логично использовать наш блок `.card` снова. Ставим его туда, и наша сетка "едет": оказывается, там меньше места, и нам нужна карточка 280 пикселей шириной. Но из-за заданного размера карточка "торчит" из контейнера.

![https://user-images.githubusercontent.com/37917037/127750221-7c75880d-5832-4b36-acc4-a071c24fc080.png](https://user-images.githubusercontent.com/37917037/127750221-7c75880d-5832-4b36-acc4-a071c24fc080.png)

Поэтому у блока размеров быть не должно: БЭМ-блок `.card` должен подстроиться под ширину кониейнера или колонки, в котором он находится: эти размеры определяются тем контекстом, в котором мы его используем.

Аналогичная ситуация и с отступами (но пример с размером более нагляден). Отступы так же должны быть определены контекстом, в котором использован БЭМ-блок: через элементы или gap'ы в сетке. Блок не должен ничего сдвинуть или сместить в своем окружении.

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
Здесь надо отметить, что на защите тебя скорее всего по этим нюансам проверять не будут, потому что в академии ограничиваются проверкой нейминга и файловой структуры по БЭМ.

Поэтому, тебе нужно будет сообщить мне — хочешь ли ты попробовать по максимуму соответствовать принципам БЭМ, или же, если это пока кажется сложным, мы можем ограничиться более простыми правилами (ты так же можешь отказаться от соблюдения этого позже, если станет тяжело).

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/title.scss
> +  margin: 0;
Есть проблема не только с установкой, но и с обнулением отступов у БЭМ-блоков. Хотя, казалось бы обнуление — это же не установка отступа, а удаление?..

Но суть проблемы в том, что обнуление внутри блока точно так же может случайно переписать свойства элемента, как и указание какого-то конкретного размера.
Потому что технически мы не обнуляем, а назначаем отступ, равный нулю. Поэтому даже обнуления придется делать через элементы.

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/tabs.scss
> +  height: 43px;
Каждая из этих кнопок — один и тот же элемент интерфейса.
Не надо делать их разными. Надо сделать одинаковыми, а иконку поставить в середину кнопки.

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/tabs.scss
> +  height: 32px;
Не стоит повторять одни и те же стили, все это вполне можно унести в класс элемента (заодно и размер одинаковый сделать), оставить в модификаторе только картинку

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/tabs.scss
> +  margin-left: 37px;
Не стоит сейчас только отступами пытаться попадать в макет. У нас для этого будут сетки.
Отступы вообще лучше ставить внутренние сейчас в основном там, где нужно показать фон. Остальное — преждевременно

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  font-weight: bold;
Стоит использовать для шрифтов один вид значений.
Типа, или мы пишем ключевые слова, то пишем всегда их, если цифры — то их. Учитывая, что слова есть далеко не для всего, обычно просто пишут цифры )
`bold` это `700`
`normal` это `400`

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +}
Это уже не элемент и вообще не часть блока `modal`, поэтому в этом файле оно быть не может

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  min-height: 63px;
Как-то странновато. Не должна ли высота исходить из отступов ссылки?

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +
А почему тут пустая строка в начале?

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/footer-social.scss
> +  margin-right: 14px;
Вот только все это — часть интерактивного элемента (ссылки), а не элемента списка

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  font-family: "Open Sans", "Arial", sans-serif;
Какое-то невообразимое количество стилей для модификатора

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/download.scss
> +  width: 33.33%;
Опять же, следы того, что ты пытаешься зачем-то располагать элементы как на макете.
У нас нет такой задачи сейчас, а эти стили в будущем больше помешают работе с сетками, чем помогут чем-либо.

2021-12-10 18:47 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  height: 59px;
Задать всему блоку сразу же ширину и высоту — это смело )
Думаешь, не будет кнопки с более широким текстом или текстом, который слетит на вторую строку?

2021-12-10 19:35 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +          <button class="tabs__tab  tabs__tab--contrast" role="tab" aria-selected="false" aria-controls="contrast-panel" id="contrast-tab">
удалила лишний пробел

2021-12-10 19:36 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +      <h1 class="title">Фотографии
вернула назад

2021-12-10 19:40 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +      <p class="post__title">Затмите их всех!<br>
удалила везде

2021-12-10 19:40 UTC, DaryaNikolaeva31 commented on source/form.html
> +        путешествие с Пинк</h1>
вернула назад

2021-12-10 19:42 UTC, DaryaNikolaeva31 commented on source/index.html
> +        </li>
точно заглушка? есть же целое демо-на добавление только карты через iframe

2021-12-10 19:47 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
хочу попробовать по-максимуму соответствовать принципам пока это возможно!

2021-12-10 19:47 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
вопрос: если отступы тоже в сетках делаются-то зачем в данном задании указано было проставить отступы?

2021-12-10 19:50 UTC, wrgraff commented on source/index.html
> +        </li>
Так это карту, здесь то ссылка с адреса

2021-12-10 19:51 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
> +  font-weight: bold;
я на седоне писала цифры, постоянно переписывая слова на цифры
здесь решила писать слова-везде вроде указывала только слова
слова указывать же можно?в данной ситуации, на этом проекте всего три варианта жирности?

2021-12-10 19:52 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
Какие-то отступы можно найти. Там, внутренние отступы кнопок, например. Но вертикальные отступы между колонками, например, делать рановато — нам нужна сетка, чтобы понять как и какие отступы использовать, и не сделать ли их гэпами, и бла-бла-бла

2021-12-10 19:53 UTC, DaryaNikolaeva31 commented on source/sass/blocks/download.scss
> +  width: 33.33%;
удалила ширину

2021-12-10 19:55 UTC, DaryaNikolaeva31 commented on source/sass/blocks/button.scss
> +  height: 59px;
ну я посмотрела, что у меня всего три такие кнопки и только на странице конкурса, подумала, что в данном случае-можно)
удалила)

2021-12-10 19:59 UTC, DaryaNikolaeva31 commented on source/sass/blocks/field.scss
> +  font-family: "Open Sans", "Arial", sans-serif;
и правда...
оставила высоту, паддинги и шрифт

2021-12-10 20:05 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +
убрала
странно, что проверка мне этого не показала, ведь лишние последние строки она показывает

2021-12-10 20:05 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  min-height: 63px;
убрала высоту

2021-12-10 20:07 UTC, DaryaNikolaeva31 commented on source/sass/blocks/modal.scss
> +}
меня периодически клинит на подчеркиваниях/двойных дефисах(
исправила на modal__content

2021-12-10 20:08 UTC, DaryaNikolaeva31 commented on source/sass/blocks/tabs.scss
> +  margin-left: 37px;
удалила

2021-12-10 20:11 UTC, DaryaNikolaeva31 commented on source/sass/blocks/tabs.scss
> +  height: 32px;
сделала как ты написал

2021-12-10 20:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/tabs.scss
> +  height: 43px;
вроде сделала

2021-12-10 20:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  margin: 0;
это не очень поняла

2021-12-10 20:13 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  width: 320px;
удалила ширину

2021-12-10 20:15 UTC, DaryaNikolaeva31 commented on source/sass/fonts.scss
> +    url("/source/fonts/opensansbold.woff");
проверка гитхаба ругалась, изначально я так и делала

2021-12-10 20:18 UTC, DaryaNikolaeva31 commented on source/sass/fonts.scss
> +  src: url("/source/fonts/opensans.woff2"), url("/source/fonts/opensans.woff");
исправила ../fonts/opensanslight.woff2

2021-12-10 20:20 UTC, DaryaNikolaeva31 commented on source/sass/global/variables.scss
> +@mobile-width-only: 320px;*/
я, честно говоря, вообще не поняла, зачем применять переменные, если можно значение просто указать, не понимаю, в чем удобство использования и зачем это надо
не знала, что тут писать, а проверка ругалась на пустой файл
у кого-то стащила(

2021-12-10 20:21 UTC, DaryaNikolaeva31 commented on source/sass/style.scss
> +@import "./global/variables";
вообще забыла про верхние строчки...)

2021-12-10 20:23 UTC, DaryaNikolaeva31 commented on source/sass/style.scss
> +@import "./fonts.scss";
могу переименовать в common?global-странновато звучит при трех страницах то)
я не знала, куда их поместить, посмотрела у кого-то на гитхабе из академии-куда их засосывают
сейчас переделаю

2021-12-10 20:30 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +  list-style-type: none;
ok

2021-12-10 20:56 UTC, DaryaNikolaeva31 commented on source/catalog.html
> +        <li class="footer-social__item footer-social__item--twitter">
исправила

2021-12-10 21:10 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="download__item  download__item--microsoft">
сделала, но иконки не показываются(

2021-12-10 21:11 UTC, DaryaNikolaeva31 commented on source/sass/global/variables.scss
> +/*@tablet-width: 660px;
я читала ее

2021-12-10 21:23 UTC, DaryaNikolaeva31 commented on source/sass/global/variables.scss
> +/*@tablet-width: 660px;
добавила 1 пока что

2021-12-10 21:25 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  text-align: center;
не поняла
модификатор этот используется на главной в двух местах

2021-12-10 21:28 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  padding-bottom: 70px;
оставила только цвет

2021-12-10 21:31 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  padding-bottom: 70px;
по поводу отступа для блока-ты имеешь ввиду для первого заголовка на главной?его заключить в отдельный блок, чтобы его повторять на страницах с фоновой картинкой?

2021-12-10 21:33 UTC, DaryaNikolaeva31 commented on source/index.html
> +        </li>
добавила ссылку на адрес

2021-12-10 21:35 UTC, DaryaNikolaeva31 commented on source/sass/blocks/footer-social.scss
> +  margin-right: 14px;
переделала

2021-12-10 23:54 UTC, wrgraff commented on source/index.html
> +        <li class="download__item  download__item--microsoft">
Значит не все учла.
Вспоминай, чем базовые стили ссылки отличаются от элемента списка

2021-12-10 23:55 UTC, wrgraff commented on source/sass/style.scss
> +@import "./fonts.scss";
Ну тут вроде как принято называть `global`. Что странно, так как стили глобальны все: они все для всего проекта. А тут скорее "общие", типа общие для всех блоков.

2021-12-10 23:58 UTC, wrgraff commented on source/sass/global/variables.scss
> +@mobile-width-only: 320px;*/
Переменные нужны чтобы в процессе поддержки проекта при изменении какого-то значения (например — обновления цветовой схемы) не менять их везде, а поменять только значение переменных.

Кроме того, это приучает держать определенное количество цветов, и не позволит создать 18 лишних оттенков.

В учебном проекте острой необходимости в этом конечно нет, но в нем вообще во многих штуках острой необходимости нет.

2021-12-10 23:59 UTC, wrgraff commented on source/sass/global/variables.scss
> +/*@tablet-width: 660px;
1 цвет?
Добавь лучше все цвета. Когда тебе понадобятся переменные (а то и вовсе кастомные свойства), разбираться как это работает будет некогда

2021-12-11 00:00 UTC, wrgraff commented on source/sass/fonts.scss
> +    url("/source/fonts/opensansbold.woff");
Ты наверное значение во второй строке сдвигала под значение первой.
Тут предложение иное

2021-12-11 00:01 UTC, wrgraff commented on source/sass/blocks/title.scss
> +  text-align: center;
Модификатор **не используется без основного класса** `title`. Соответственно, повторять в нем свойства, которые уже есть в `title` — бессмысленно

2021-12-11 00:02 UTC, wrgraff commented on source/sass/blocks/title.scss
> +  padding-bottom: 70px;
Да, скорее всего так и будет. Но это можно сделать и на следующем шаге

2021-12-11 00:07 UTC, wrgraff commented on source/sass/blocks/title.scss
> +  margin: 0;
Это влияет на внешнее поведение блока.

В какой-то момент, в зависимости от порядка подключения файлов, стили блока могут переписать стили элемента. В таком случае внешний отступ контролировать через элемент не получится, что в методологии БЭМа станет проблемой

2021-12-11 00:08 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  font-weight: bold;
Третий вариант — `300`, у него нет ключевого слова в CSS

2021-12-11 00:08 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +}
Но тут то один дефис

2021-12-11 00:09 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +
Проверка довольно тупая =)

2021-12-11 00:10 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  font-family: "Open Sans", "Arial", sans-serif;
Шрифт?
А чего бы не написать его в основном классе?

И не помню, кстати, чтобы в задании было указание задавать высоту...

2021-12-11 00:11 UTC, wrgraff commented on source/sass/blocks/button.scss
> +  height: 59px;
А потом на новой странице проекта появится еще 23 такие кнопки с разными текстами и разной адаптивностью...

2021-12-11 10:36 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
> +  font-weight: bold;
Разве не light?
В каком-то из лайвов это было
Ну ладно, переделаю на цифры

2021-12-11 19:49 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="download__item  download__item--microsoft">
w/h с item перенесла на link

2021-12-11 19:50 UTC, DaryaNikolaeva31 commented on source/sass/style.scss
> +@import "./fonts.scss";
ok

2021-12-11 20:29 UTC, DaryaNikolaeva31 commented on source/sass/global/variables.scss
> +/*@tablet-width: 660px;
ок, добавила все цвета, что нашла, поменяла цвета во всех файлах на переменные

2021-12-11 20:30 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  text-align: center;
ок, поняла, удалила, оставила только цвет

2021-12-11 20:37 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  padding-bottom: 70px;
добавила отдельный блок для заголовка

2021-12-11 20:39 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  margin: 0;
удалила тут марджин
я поняла, что у блока не должно быть внешних границ
получается у всех блоков удаляю марджины?

2021-12-11 20:49 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
> +  font-weight: bold;
поменяла на цифры

2021-12-11 20:52 UTC, DaryaNikolaeva31 commented on source/sass/blocks/field.scss
> +  font-family: "Open Sans", "Arial", sans-serif;
убрала высоту в обоих классах, шрифт перенесла в основной класс, остались только паддинги

2021-12-11 21:34 UTC, DaryaNikolaeva31 commented on source/sass/blocks/title.scss
> +  margin: 0;
удалила везде марджин

2021-12-12 16:09 UTC, wrgraff commented on source/index.html
> +          </p>
Я бы наверное рекомендовал оформить эти элементы идентично. Ну и `<address>` в каждом это кажется ту мач...

2021-12-12 16:09 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> -  margin: 0;
А зачем удалила отступы?
`.advantages__list` — это же элемент, а не блок

2021-12-12 16:09 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +  list-style-type: none;
И не изменила )

2021-12-12 16:09 UTC, wrgraff commented on source/sass/global/variables.scss
> +$green-800: #2aab6d;
Не понимаю, используешь ли ты именования или цифровую систему.
И то и другое одновременно используется сейчас.

2021-12-12 16:09 UTC, wrgraff commented on source/sass/blocks/tabs.scss
> +  height: 48px;
Во, отлично

2021-12-12 16:09 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  font-weight: bold;
light это название, да. Но работать в коде оно не будет.

2021-12-12 16:14 UTC, wrgraff approved these changes

2021-12-12 16:14 UTC, wrgraff commented on source/sass/blocks/footer-social.scss
> +  height: 48px;
А как это будет работать?
Размер разве нужен обертке интерактивного элемента, а не самому элементу?

2021-12-12 16:14 UTC, merged

2021-12-12 19:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +  list-style-type: none;
так а надо?ты просто написал, что так проще, я думала впредь так писать
или мне все поменять?

2021-12-12 19:21 UTC, DaryaNikolaeva31 commented on source/sass/global/variables.scss
> +$green-800: #2aab6d;
и то и то одновременно нельзя использовать?

2021-12-12 19:33 UTC, DaryaNikolaeva31 commented on source/sass/blocks/footer-social.scss
> +  height: 48px;
ок, размеры перенесла на ссылку

2021-12-12 19:42 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +  list-style-type: none;
поменяла

2021-12-12 19:47 UTC, DaryaNikolaeva31 commented on source/index.html
> +          </p>
address оставила только у адреса на карте
и элементы оформила вроде более-менее одинаково

2021-12-12 19:56 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> -  margin: 0;
спискам вернула нулевой марджин

2021-12-13 19:59 UTC, DaryaNikolaeva31 commented on source/sass/global/variables.scss
> +$green-800: #2aab6d;
цифровая система мне как-то не зашла) сделала именования, все равно переменных мало