Адаптивная сетка для главной страницы
htmlacademy-adaptive/142152-pink-24 pull request #5
Opened 2021-12-13 20:05 UTC by DaryaNikolaeva31

2021-12-16 23:55 UTC, wrgraff requested changes
Самая большая проблема сейчас, с которой стоит начать в первую очередь (так как ее исправление будет ломать все подряд) — это отсутствие центрирования контента сайта

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    padding-right: 154px;
По этим отступам сразу ряд ошибок виден.
Во-первых, они неправильно посчитаны. Если включить направляющие, то будет видно что до контента отступ 130 точек, а вовсе не 154:
<img width="1098" alt="изображение" src="https://user-images.githubusercontent.com/37917037/146460976-c30d431e-d5e0-42dd-8b72-f0cc6924d969.png">
Нужно различать границу контента и границу текстового блока.

Далее, из этого мы можем сделать вывод, что колонки у нас должны быть не в ширину текстового блока, а такой ширины, чтобы текстовый блок стоял по центру, а сами колонки упирались в границы контентной области:
<img width="1095" alt="изображение" src="https://user-images.githubusercontent.com/37917037/146461250-5beed21e-2dfd-419b-8821-ea424a54ebe9.png">

Ну и на самом деле у тебя ширина контентной области должна быть ограничена в 940 пикселей. Сейчас же сайт тянется в ширину без пределов.
И это так же значит, что отступы по 130 пикселей тоже вовсе не обязательны. Например, сайт вполне нормально будет работать и при отступах в 40 пикселей от краев контента, то есть — начиная с 1020 пикселей. А на 1200 отступы все равно будут как на макете

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +@media (min-width: $desktop-width) {
Как по мне, так писать сперва мобильные стили для всех классов, потом все стили для планшета, а потом все стили для десктопа — самый неудобный вариант из возможных.
Что, если нам для красивой резины еще промежуточные запросы понадобятся для отдельных классов? Будет чуть больше хаоса.
А еще, насколько удобно будет править верстку какого-нибудь класса `.reviews`? Очень часто надо что-то менять в мобильной и сразу же в планшетной и десктопной версии. Например, везде уменьшить какой-нибудь отступ на 10 пикселей. Будет не очень удобно, если нужны код разбросан по всему файлу...

Но тут конечно как хочешь )

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +  }
Есть подозрение, что работу `order` ты не полностью осознала.
Например, `.reviews__title` и `.reviews__subtitle` местами не меняются, а значит между собой идут в порядке разметки. Так зачем им разный вес порядка? И не проще ли наоборот текст вытаскивать наверх?

Рекомендую [почитать про order](https://frontend-design.notion.site/order-210af6e1767c421496f883502b0e8bee)

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/price.scss
> +    padding: 70px 20px;
Как-то нехорошо, что ты пишешь свойство то так, то сяк:
https://github.com/htmlacademy-adaptive/142152-pink-24/blob/9cbba3509cc725fedd2c402276caf3812badf1cd/source/sass/blocks/price.scss#L8
https://github.com/htmlacademy-adaptive/142152-pink-24/blob/9cbba3509cc725fedd2c402276caf3812badf1cd/source/sass/blocks/price.scss#L12-L15

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/price-list.scss
> +  background-image: url("/source/img/hit.svg");
Неправильный путь к файлу. Препроцессор не умеет при сборке переписывать пути к картинкам. Это обычная статическая строка. Поэтому нам нужно писать путь исходя из того, где находится наш скомпилированный css-файл.

У нас директория `img` находится обычно рядом с директорией `css`, а значит нужно один раз выйти из директории(`../`) и зайти в картинки.

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/price-list.scss
> +  height: 59px;
Не надо прописывать ячейкам высоту.
Они в принципе и не послушаются, и если что просто вырастут вверх.
Но еще проблема в том, что прописав высоту никто не думает больше о переполнении и о том, что содержимое прилипнет к краям ячейки (расстояние между строками текста не должно быть больше расстояния до границ ячеек):
<img width="332" alt="изображение" src="https://user-images.githubusercontent.com/37917037/146463704-553e4de4-1f49-471e-8db6-720565a0c29e.png">

Если бы ты добивалась правильных размеров отступами, то все бы было сильно лучше в этом плане

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/price-list.scss
> +  height: 21px;
Ты меняешь размеры не иконкам, а самом ячейкам. Это конечно не работает, потому что это таблица и они обязаны быть одной высоту, но это — ошибка

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba(255, 255, 255, 0.15);
У тебя, кстати. можно было бы применить подход с переменной не `mobile-only`, а `tablet-down`.
Например, эти границы между пунктами нужны по сути только на телефоне и планшете. Чтобы их не обнулять на десктопе, можно сразу задать такой медиа-запрос, чтобы они рисовались на планшете и ниже.

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
Ну какой же это грид? Он создает равные колонки с равными отступами.
Отступы то у нас конечно равны, но вот ширина пунктов зависит от их содержимого. А у тебя выходит не так

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/information.scss
> +  }
А почему самому блоку ты задала отступы изначально, а всем остальным только внутри медиа-запроса?

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/information.scss
> +    display: block;
У тебя же уже задана блоку видимость в предыдущем медиа-запросе.
Этот медиа-запрос не отменяет правила предыдущего, а лишь дополняет их

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/footer-social.scss
> +  }
А как-то пооптимальнее их во флексе разве не отцентрировать?..
Это так странно, что хоть и не нарушает критериев, поставлю как обязательное

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    display: grid;
Оставь их флексом, зачем на грид переходить?
Здесь нет же в нем особой нужды, достаточно поменять ширину элементов

2021-12-16 23:55 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    justify-items: center;
Даже если меняешь флекс на грид — зачем эти свойства прописывать заново?
Они ж не меняются

2021-12-17 20:24 UTC, DaryaNikolaeva31 commented on source/sass/blocks/price-list.scss
> +  background-image: url("/source/img/hit.svg");
поправила

2021-12-17 20:26 UTC, DaryaNikolaeva31 commented on source/sass/blocks/price-list.scss
> +  height: 59px;
убрала высоту

2021-12-17 20:29 UTC, DaryaNikolaeva31 commented on source/sass/blocks/price-list.scss
> +  height: 21px;
ошибка-то, что я прописала ширину ячейке?то есть у ячеек в таблице не надо указывать ни высоту ни ширину?

2021-12-17 20:31 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba(255, 255, 255, 0.15);
сделала вот так 
@media (min-width: $mobile-width-only){
  box-shadow:
    0 1px 0 #000000,
    inset 0 1px 0 rgba(255, 255, 255, 0.15);
  }

2021-12-17 20:40 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
я пробовала разные варианты, остановилась на гриде, но ширина пунктов, зависящих от содержания-осталась без ответа)
исправила на flex

2021-12-17 20:43 UTC, DaryaNikolaeva31 commented on source/sass/blocks/information.scss
> +  }
хороший вопрос)
исправила

2021-12-17 20:44 UTC, DaryaNikolaeva31 commented on source/sass/blocks/information.scss
> +    display: block;
поправила

2021-12-17 21:00 UTC, DaryaNikolaeva31 commented on source/sass/blocks/contacts.scss
> +    display: grid;
заменила

2021-12-17 21:00 UTC, DaryaNikolaeva31 commented on source/sass/blocks/contacts.scss
> +    justify-items: center;
удалила

2021-12-17 21:10 UTC, DaryaNikolaeva31 commented on source/sass/blocks/footer-social.scss
> +  }
заменила на justify-content: center;

2021-12-17 21:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/price-list.scss
> +  height: 21px;
если мне надо прописать размеры иконок, то это background-size же или нет?
я сейчас прописала, но размер картинок не изменился(

2021-12-17 21:16 UTC, DaryaNikolaeva31 commented on source/sass/blocks/price.scss
> +    padding: 70px 20px;
исправила

2021-12-17 21:22 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
> +  }
я поняла, что ты имеешь ввиду, сделала тексту порядок -1, а у остальных-убрала, то есть у них ноль, значит текст встанет в начало списка

2021-12-17 21:25 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
> +@media (min-width: $desktop-width) {
я не поняла, что ты имеешь ввиду

и еще вопрос: в этом же суть задания, сначала делаем мобильную версию, потом редактируем для планшета, затем для десктопа
почему тогда нас учат самому неудобному способу из возможных?

2021-12-17 21:27 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    padding-right: 154px;
я не поняла, почему в итоге отступы вообще не нужны

2021-12-17 21:43 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="contacts__item contacts__item--second-order">
сделала вот так
.contacts__item--address {
  @media (min-width: $mobile-width-only) {
    order: 1;
  }
}
но почему-то на мобилке порядок не меняется, остается как на десктопе

2021-12-18 12:47 UTC, wrgraff commented on source/index.html
> +        <li class="contacts__item contacts__item--second-order">
Потому что медиа-запрос написан неправильно.
Другие запросы пишутся в формате "от такой-то точки и больше", в коде это `@media (min-width: XXXpx)`
Сейчас у тебя запрос в формате "до такой то-то точки и менее". Как это представить в коде в таком случае?

2021-12-18 12:47 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    padding-right: 154px;
Нигде не написано, что они не нужны =(

2021-12-18 12:47 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    padding-right: 154px;
Я написал, что можно их сделать меньше

2021-12-18 12:50 UTC, wrgraff commented on source/sass/blocks/reviews.scss
> +@media (min-width: $desktop-width) {
Я имею ввиду группировку кода.
С порядком написания кода это никак не связано.

[В демо](https://up.htmlacademy.ru/adaptive/24/demos/5627#11), насколько я вижу, ничему подобному вас не учат, медиа-запросы там написаны прямо внутри класса:
<img width="412" alt="изображение" src="https://user-images.githubusercontent.com/37917037/146641715-3d74af34-5475-4860-83a8-559376be8631.png">

2021-12-18 12:53 UTC, wrgraff commented on source/sass/blocks/price-list.scss
> +  height: 21px;
Прописать ширину ячейке вполне можно.

Учитывая то, как перестраиваются эти ячейки на телефоне, иконки стоит делать псевдоэлементами, а не фоном самих ячеек. Так будет попроще с текстом совладать.
<img width="403" alt="изображение" src="https://user-images.githubusercontent.com/37917037/146641799-11a21273-4fff-49b8-b5ba-c5d7b9da526b.png">

2021-12-18 12:54 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba(255, 255, 255, 0.15);
Но ведь mobile-only **не** подходит

2021-12-18 18:40 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="contacts__item contacts__item--second-order">
до какой-то точки это max-width наверное
@media (max-width: $mobile-width-only) не сработал

2021-12-21 16:17 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
> +@media (min-width: $desktop-width) {
переделала

2021-12-21 16:45 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <li class="contacts__item contacts__item--second-order">
$tablet-width-down

2021-12-21 16:47 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +    inset 0 1px 0 rgba(255, 255, 255, 0.15);
$tablet-width-down

2021-12-22 21:40 UTC, wrgraff requested changes

2021-12-22 21:40 UTC, wrgraff commented on source/index.html
> +        <div class="">
А какой класс то?

2021-12-22 21:40 UTC, wrgraff commented on source/index.html
> +          <button type="button" class=""></button>
Не, ну это халтура )
Придумай классы и контент там должен быть же какой-то

2021-12-22 21:40 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    width: 940px;
А зачем в сам блок ширину прописала?
Центровшик то внутри. В результате серый фон не тянется, контент внутри — не центрируется:
![изображение](https://user-images.githubusercontent.com/37917037/147156802-db7b49ce-015a-4ea2-af87-62c3d6346ca6.png)

2021-12-22 21:40 UTC, wrgraff commented on source/sass/blocks/information.scss
>      padding-right: 166px;
Зачем эти отступы по краям? У нас же есть центровщик.
И почему они разные? О_о

2021-12-22 21:40 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
>      margin: 0;
Обнуляешь отступы для обертки — ломаешь центрирование

2021-12-22 21:40 UTC, wrgraff commented on source/sass/blocks/advantages.scss
> +    padding-right: 130px;
Мы даже обсуждали, что отступы то и не нужны.
Максимум — сместят что-то когда это не надо

2021-12-22 21:40 UTC, wrgraff commented on source/sass/blocks/price.scss
Неплохо бы добавить `overflow: hidden;` для блока, так как иначе таблица создает горизонтальную прокрутку.

https://user-images.githubusercontent.com/37917037/147158291-5cf830cf-3232-45a1-b595-3dbb34b11f70.mov

2021-12-23 10:22 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <div class="">
ой, караул
совсем забыла про них

2021-12-23 10:33 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <div class="">
добавила класс

2021-12-23 10:33 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <button type="button" class=""></button>
да вообще ужжас, забыла про них
как и всегда
проставила классы и контент скрытый

2021-12-23 10:36 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    width: 940px;
убрала

2021-12-23 10:38 UTC, DaryaNikolaeva31 commented on source/sass/blocks/information.scss
>      padding-right: 166px;
убрала

2021-12-23 10:39 UTC, DaryaNikolaeva31 commented on source/sass/blocks/page-footer.scss
>      margin: 0;
удалила

2021-12-23 10:42 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    padding-right: 130px;
да, я помню
но почему-то не убрала сразу, глупая
удалила

2021-12-23 10:46 UTC, DaryaNikolaeva31 commented on source/sass/blocks/price.scss
добавила
а это всегда надо добавлять чтобы избежать горизонтальной прокрутки?

2021-12-23 17:40 UTC, wrgraff commented on source/sass/blocks/price.scss
Не, только если у нас есть по задумке такой вот выходящий за границы элемент.
В слайдерах всяких такое бывает

2021-12-23 17:47 UTC, wrgraff approved these changes

2021-12-23 17:47 UTC, wrgraff commented on source/index.html
> +        <div class="price-buttons">
Такие же кнопки есть в отзывах. Можно их унифицировать.
Например, сделать блок `slider-nav` и кнопки внутри будут `slider-nav__button`

2021-12-23 17:47 UTC, wrgraff commented on source/index.html
> +          <button type="button" class="price-buttons__unlime">
А зачем каждая кнопка — новый элемент?
Почему они не могут быть все одним и тем же элементом? Выглядят то они одинаково. Кроме выбранного. Но там модификатор

2021-12-23 17:47 UTC, wrgraff commented on source/index.html
> +            <span class="visually-hidden">Кнопка назад</span>
Плохое описание. Никакая это не "кнопка вперед".
Это кнопка, включающая первый тариф. Вне зависимости от того, что сейчас выбрано — средняя, последняя или она сама, она всегда будет выбирать определенный тариф.

И еще. По правилам UX кнопки должны быть подписаны глаголом, потому что они совершают какое-то действие.

2021-12-23 17:47 UTC, merged