Декоративные элементы главной страницы
htmlacademy-adaptive/142152-pink-24 pull request #7
Opened 2022-01-17 21:52 UTC by DaryaNikolaeva31

очень много вопросов и ошибок
я сделала все три страницы(протупила)
больше всего вопросов наверно по десктопу
+я так и не смогла найти причину, почему на мобильной версии бэкграунд в обертках отъехал по бокам(

2022-01-18 20:57 UTC, wrgraff requested changes
А где в таблице все эти галочки и крестики?
Кстати, по правильным скруглениям [есть плейлист тоже](https://youtube.com/playlist?list=PL6xpnt2woRKm3kTayObm0L_8COGsEK1UL): можешь подсмотреть их реализацию (хотя многие не делают и прокатывает)

Я пока рассмотрел только явные косяки по коду. И пока только для главной — столько сразу пока не будем проверять, начнем с нее.

По косякам самой верстки запишу ревью.

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    order: 2;
С ордерами перегибы. Используешь их как порядковый номер элемента.
Это не то чтобы запрещается, но говорит о плохом понимании того, как именно работает `order`.

Я уже давал [почитать про ордер](https://paper.dropbox.com/doc/order--BaRAJIeRO8QraZbHqTX0Rk5OAQ-mBkmustOVfjTyjGWLpBXQ)?

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/contacts.scss
> +    padding-top: 61px;
Я не понимаю систему отступов.
Почему _между_ элементами внутренний отступ?
Почему они заданы модификаторам? Ведь по идее они не должны зависеть от содержимого

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/footer-social.scss
> +  border: 3px solid rgba(40, 54, 69, 0.1);
А ты знаешь, что благодаря препроцессору можно делать так:
```suggestion
  border: 3px solid rgba($midnight, 0.1);
```

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/information.scss
> +  background-image: url("../img/24.svg");
А куда полоса то красная пропала с картинки? Там внутренний круг был красный:
![изображение](https://user-images.githubusercontent.com/37917037/150011361-26c7bc69-b379-44ac-bcde-f3e1d0b6b134.png)

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  }
Артур:
> Состояния, связанные с свг, я пока рекомендую не делать. До лайва про спрайты точно не стоит этого касаться

Дарья:
`fill: bla-bla-bla`

Ну ты чего =)

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    fill: fade($cerise, 30%);
`fade()` это ж вообще less. А в Sass есть `rgba()`

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    fill: $cerise;
Если ты так хочешь подействовать на картинку в фоне, то ничего не выйдет. Картинка в фоне — всего лишь картинка, воспринимаемая как внешний ресурс. Ты можешь управлять ее расположением через свойства фона, но ей самой — нет

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  height: 23px;
Лучше не менять геометрию элемента, а просто поставить фоновую картинку так, чтобы попала в макет.
В этом есть и косяк дизайна: он не должен провоцировать на такую реализацию со смещением кнопки.

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +
Ну а позиционировать то модалку по центру экрана не надо ли? =)

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/reviews.scss
>  }
А где декор? Кавычка вот эта перед текстом.
И кнопки пролистывания слева и справа.
![изображение](https://user-images.githubusercontent.com/37917037/150013252-6ad23b8f-34b8-438b-a36f-894fa50257dc.png)

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/switch-buttons.scss
> +  width: 100%;
Это обычный блочный див, зачем ему это?

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/switch-buttons.scss
> +.switch-buttons--price {
Отображением навигации внутри слайда лучше бы управлять через элемент блока.
Блок не должен знать в каком он там случае показывается, а в каком нет. Так получается его надо модификаторами обвешать в каждом новом месте. А правильнее будет его миксовать с элементом и через элемент управлять отображением

2022-01-18 20:57 UTC, wrgraff commented on source/sass/blocks/text-block.scss
> +    width: 300px;
Блок не должен управлять своей шириной.
И как раз здесь наглядный пример почему. Ты ограничила ширину блока везде. А она ограничивается только на главной. Переиспользуемость очень наглядно ломается )

2022-01-19 20:44 UTC, DaryaNikolaeva31 commented on source/index.html
> +    </div>
я хотела объединить эти два блока и дать им один бэкграунд(

*закрыла в хедере его

2022-01-19 20:45 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <div class="switch-buttons switch-buttons--reviews">
убрала

2022-01-19 20:46 UTC, DaryaNikolaeva31 commented on source/index.html
> +          </button>
я ни у кого не слизываю, нет времени искать)
исправила на "смотреть 1 отзыв"

2022-01-19 20:58 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <button type="button" class="switch-buttons__main switch-buttons__main--current">
заменила на switch__buttons--current

2022-01-19 20:59 UTC, DaryaNikolaeva31 commented on source/index.html
> +            <span class="visually-hidden">Выбранная опция</span>
заменила

2022-01-19 21:02 UTC, DaryaNikolaeva31 commented on source/index.html
> +        <div class="switch-buttons switch-buttons--price">
заменила
![image](https://user-images.githubusercontent.com/89548917/150213266-6fe4a06b-f533-4698-a55d-c05c030aedd0.png)

2022-01-19 21:04 UTC, DaryaNikolaeva31 commented on source/js/script.js
> +    });
нажала еще раз отформатировать с помощью stylelint

2022-01-19 21:06 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
>    }
размер и картинки ты мне говорил оставить на попозже, когда я перейду к ним
про логотип же ты не спрашиваешь, почему он не меняется с изменением устройства и разрешения

2022-01-19 21:07 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +@media (min-width: $desktop-width) {
нужно придерживаться исключительно одного варианта? нельзя для удобства использовать оба?

2022-01-19 21:09 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +  background-position: bottom;
указала center

2022-01-19 21:10 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    background-position: left;
по умолчанию center
добавила его

2022-01-19 21:15 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    background-position: top;
исправила

2022-01-19 21:16 UTC, DaryaNikolaeva31 commented on source/sass/blocks/contacts.scss
> +    align-items: baseline;
исправила

2022-01-19 21:18 UTC, DaryaNikolaeva31 commented on source/sass/blocks/footer-social.scss
> +  border: 3px solid rgba(40, 54, 69, 0.1);
не знала
исправила

2022-01-19 21:19 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  }
это я сделала до того, как ты мне это написал)

2022-01-19 21:20 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  }
закомментила пока, потом исправлю!не забуду!

2022-01-19 21:21 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +    fill: fade($cerise, 30%);
я это из лайва копировала(

2022-01-19 21:22 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +    fill: fade($cerise, 30%);
исправила на rgba

2022-01-19 21:23 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +    fill: $cerise;
это не очень поняла, но думаю, когда делать начну-пойму

2022-01-19 21:24 UTC, DaryaNikolaeva31 commented on source/sass/blocks/switch-buttons.scss
> +  width: 100%;
удалила

2022-01-20 12:50 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +@media (min-width: $desktop-width) {
поправила
![image](https://user-images.githubusercontent.com/89548917/150341885-61813a26-86d6-40ef-920f-a3818d035821.png)

2022-01-20 13:17 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    background-image: url("../img/rise.png");
а я невнимательно смотрела макет и тень на картинках и серую плашку вообще не заметила)

2022-01-20 13:45 UTC, DaryaNikolaeva31 commented on source/sass/blocks/contacts.scss
> +    order: 2;
да, давай почитать
я забыла
исправила!

2022-01-20 21:18 UTC, DaryaNikolaeva31 commented on source/sass/blocks/text-block.scss
> +    width: 300px;
удалила

2022-01-20 21:30 UTC, DaryaNikolaeva31 commented on source/sass/blocks/main-nav.scss
> +  height: 23px;
ok

2022-01-21 19:58 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
>    }
добавила на планшете другой размер

2022-01-21 19:59 UTC, DaryaNikolaeva31 commented on source/sass/blocks/information.scss
> +  background-image: url("../img/24.svg");
исправила

2022-01-21 20:23 UTC, DaryaNikolaeva31 commented on source/sass/blocks/switch-buttons.scss
> +.switch-buttons--price {
типа такого?
class="switch price-list__buttons"
![image](https://user-images.githubusercontent.com/89548917/150595241-a4f50d13-d09b-4393-8206-2116551a9d12.png)

2022-01-21 20:54 UTC, DaryaNikolaeva31 commented on source/index.html
> +    </div>
удалила его

2022-01-21 21:11 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
>    }
заменила картинки посмотрев твое видео про картинки)спасибо!

2022-01-22 19:11 UTC, DaryaNikolaeva31 commented on source/sass/blocks/advantages.scss
> +    background-image: url("../img/rise.png");
заменила картинки, спасибо!

2022-01-22 19:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/contacts.scss
> +    padding-top: 61px;
исправила

2022-01-22 19:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/reviews.scss
>  }
добавила!
не без твоей помощи)

2022-01-22 19:14 UTC, DaryaNikolaeva31 commented on source/sass/blocks/switch-buttons.scss
> +.switch-buttons--price {
до меня дошло, что именно ты имеешь ввиду и почему так и как должно быть!алиллуйя
спасибо!

*поменяла местами switch price-list__buttons

2022-01-22 19:48 UTC, DaryaNikolaeva31 commented on source/sass/blocks/modal.scss
> +
margin: auto  поставила, абсолютом не надо же?
или надо для пиксель перфекта поставить строго по макету и закомментить позицию?

2022-01-22 23:02 UTC, DaryaNikolaeva31 commented
> А где в таблице все эти галочки и крестики? Кстати, по правильным скруглениям [есть плейлист тоже](https://youtube.com/playlist?list=PL6xpnt2woRKm3kTayObm0L_8COGsEK1UL): можешь подсмотреть их реализацию (хотя многие не делают и прокатывает)
крестики/галочки добавила, бордеры и скругления вроде сделала
> 
> Я пока рассмотрел только явные косяки по коду. И пока только для главной — столько сразу пока не будем проверять, начнем с нее.
> 
> По косякам самой верстки запишу ревью.



у меня беда с switch__buttons-current-какая-то она нелепая получилась

и title--inverted- везде разные отступы-я его еще и в контактах использую, получается везде нужно добавить элемент? чтобы на него вешать отступы?

ну и картинки:
я бэкграунд главный вставила десктопный, руку сделала пнг, но на мобилке она сжимается почему-то, да и на планшете тоже

2022-01-24 17:39 UTC, wrgraff commented on source/index.html
> +          <button class="arrow-switch__buttons arrow-switch__buttons--back">
Почему множественное число, а не единственное?
```suggestion
          <button class="arrow-switch__button arrow-switch__button--back">
```

2022-01-24 17:39 UTC, wrgraff commented on source/index.html
> +            <span class="visually-hidden">Смотреть отзыв №1</span>
Ну вот ты повторяешь решение с кнопками, а логика то тут другая.
Получилось опять неправильно.

В отличие от кнопок внизу, которых столько же, сколько слайдов и которые включают конкретный слайд, это то кнопки как раз переключают слайды вперед и назад. И их всегда 2. И подписи у них вряд ли будут с номером слайда.

2022-01-24 17:39 UTC, wrgraff commented on source/index.html
> +          <button class="arrow-switch__buttons arrow-switch__buttons--next">
Кнопкам обязательно нужно прописать атрибут `type`.

По умолчанию кнопки работают как отправка формы. И если случайно из-за глюка в коде с незакрытым тегом формы наша кнопка отправит данные вместо переключения слайдера, то будет не здорово 🙃

Поэтому, таким кнопкам обязательно надо прописать `type="button"`.

Есть и еще момент. Надо прописывать и `type="submit"` тоже. Зачем прописывать значение по умолчанию?

А все просто: ради декларативности. То есть, если я посмотрю на кнопку, я *точно* буду знать какого она типа, если в ней этот тип написан. А если не написан, то буду сидеть и сомневаться: "это я забыл прописать или значение по умолчанию хотел использовать?".

2022-01-24 17:39 UTC, wrgraff commented on source/sass/blocks/map-picture.scss
> +}
Неправильно задала ширину (в том числе она правильно не работает и на мобильных).
Ты ставишь конкретную ширину в пикселях. А карта должна тянуться на всю ширину экрана. Сейчас чуть большая ширина и карта остается слева:
![изображение](https://user-images.githubusercontent.com/37917037/150832094-62e6e7aa-e36a-45b1-8c90-f9faee0754b4.png)

2022-01-24 17:39 UTC, wrgraff commented on source/sass/blocks/download.scss
> +    background-position: 208px 146px, 0 0;
Опять же, задаешь конкретные размеры, и макет не работает как нужно ни на одной ширине, кроме макетных:
![изображение](https://user-images.githubusercontent.com/37917037/150832803-db3ba8f3-df7b-4f7f-ae42-01c05d9c5938.png)

У руки должен быть размер фикс, а вот картинка фоновая со зданием должна растягиваться.

2022-01-24 17:39 UTC, wrgraff commented on source/sass/blocks/download.scss
> +    background-size: 660px 545px, 660px 729px;
Картинки искажаются, потому что размер ты им меняешь, а сами картинки — нет.
Но дело то в том, что картинки разные для разных размеров.

2022-01-24 17:39 UTC, wrgraff commented on source/sass/blocks/download.scss
> +    background-position: 0 184px, 0 0;
Рука с телефоном должна оставаться по центру, а сейчас она слева

2022-01-24 17:39 UTC, wrgraff commented on source/sass/blocks/arrow-switch.scss
> +}
Мы вот вроде только-только рядом обсуждали, что можно повторяющиеся стили выносить в класс, который будет общим, а тут опять

2022-01-24 17:39 UTC, wrgraff commented on source/sass/blocks/modal.scss
> +
Там не абсолют, там `fixed` должен быть. Потому что окно должно появиться в центре экрана вне зависимости от того, куда мы смотрим и в каком месте страницы находимся.

2022-01-24 17:40 UTC, wrgraff commented on source/sass/blocks/switch-buttons.scss
> +.switch-buttons--price {
Да, все правильно теперь!

2022-01-24 18:16 UTC, wrgraff requested changes
По кнопкам под таблицей ответил в ревью.
По картинкам в фон сжатым — тоже.

Про `title`. Если ты про то, что он с разными отступами на внутренних страницах, это не совсем так. Там не в отступах дело, а в том, что темная плашка на внутренних страницах одинаковой высоты. Даже если в ней всего одна строка текста.
Это как раз хороший пример того, где уместно использовать минимальную высоту:
![изображение](https://user-images.githubusercontent.com/37917037/150840670-9a796b0a-b7d9-4c30-a10b-84ba55685275.png)

2022-01-24 18:16 UTC, wrgraff commented on source/sass/blocks/switch.scss
> +.switch__buttons {
Посматривай иногда на блочную модель в инструментах браузера.
Например, тут видно, почему кнопку расперло в ширину:
![изображение](https://user-images.githubusercontent.com/37917037/150839074-dba4c784-b7cb-46f4-930c-b20ffaa01b97.png)

2022-01-24 18:16 UTC, wrgraff commented on source/sass/blocks/switch.scss
> +  height: 12px;
Я рекомендую не менять размеры кнопок, чтобы при изменении активности они не дергались (а то будут, ведь они то больше, то меньше становятся).

Используй оба раза 12 на 12. Мы знаем, что середина там 6 на 6, а рамка вокруг — 3.
Рамку сделать можно в цвет фона родителя, либо сделать ее прозрачной. Во втором случае так же нужно прописать это:
```css
background-clip: content-box;
```
[Это свойство определяет границы фона](https://developer.mozilla.org/ru/docs/Web/CSS/background-clip). По умолчанию он будет виден под рамкой, если она прозрачна, а так — нет.

2022-01-24 19:06 UTC, wrgraff requested changes
Нужно еще и декор в формах реализовать до конца: сделать чекбоксы и радио-кнопки.

2022-01-24 19:06 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +}
Получается, что у тебя сейчас за порядок подписи и самого инпута отвечают элементы блока `form-group`.
А тем временем, это ведь по сути элементы блока `field`, который управляет подписью и инпутом.

Лучше не смешивать и не управлять элементами одного блока через другой

2022-01-25 14:31 UTC, DaryaNikolaeva31 commented on source/sass/blocks/modal.scss
> +
сделала

2022-01-25 14:33 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <button class="arrow-switch__buttons arrow-switch__buttons--back">
ну их же две)
исправила на единственное

2022-01-25 14:43 UTC, DaryaNikolaeva31 commented on source/index.html
> +          <button class="arrow-switch__buttons arrow-switch__buttons--next">
прописала type="button"

2022-01-25 14:46 UTC, DaryaNikolaeva31 commented on source/sass/blocks/map-picture.scss
> +}
да, чет протупила
поставила width: 100%
но высоту оставляю же?

2022-01-25 14:47 UTC, DaryaNikolaeva31 commented on source/sass/blocks/map-picture.scss
> +}
если убрать высоту-ужас какой-то)

2022-01-25 16:53 UTC, DaryaNikolaeva31 commented on source/sass/blocks/download.scss
> +    background-position: 208px 146px, 0 0;
фоновой задала 100%

2022-01-25 17:06 UTC, DaryaNikolaeva31 commented on source/sass/blocks/download.scss
> +    background-size: 660px 545px, 660px 729px;
для каждого размера картинки-добавила
но при переходе от одного размера к другому-задний background "тянется", то есть само изображение растягивается( машины и люди становятся длиннее)-разве так должно быть?или я что-то не учла?

2022-01-25 17:17 UTC, DaryaNikolaeva31 commented on source/sass/blocks/download.scss
> +    background-position: 0 184px, 0 0;
я немного подвинула, 
хоть фото для планшета и поставила, но все равно выходит не как в макете, не понимаю почему
и черная полоса под рукой(

2022-01-25 17:18 UTC, DaryaNikolaeva31 commented on source/sass/blocks/arrow-switch.scss
> +}
я честно пыталась так и делать
но стоило общие стили объединить в общий класс и стрелка накладывалась одна на другую и все разваливалось(

2022-01-25 17:21 UTC, DaryaNikolaeva31 commented on source/sass/blocks/arrow-switch.scss
> +}
хм, сейчас все норм
я правда пыталась(( я не обманываю

2022-01-25 17:27 UTC, DaryaNikolaeva31 commented on source/sass/blocks/switch.scss
> +  box-shadow: 0 4px 4px rgba($black, 0.25);
она была!
удалила

2022-01-25 17:37 UTC, DaryaNikolaeva31 commented on source/sass/blocks/switch.scss
> +.switch__buttons {
padding убрала

2022-01-25 17:39 UTC, DaryaNikolaeva31 commented on source/sass/blocks/switch.scss
> +  height: 12px;
круто!спасибо!исправила

2022-01-26 19:11 UTC, DaryaNikolaeva31 commented on source/sass/blocks/contest.scss
> +  display: none;
я пока так оставлю
 если останется время-переделаю

2022-01-26 19:15 UTC, DaryaNikolaeva31 commented on source/sass/blocks/form-group.scss
> +.form-group__heading--emotions {
это принципиально?я могу заменить на feelings,например)

2022-01-26 19:32 UTC, DaryaNikolaeva31 commented on source/sass/blocks/form-сheckbox.scss
а как быть с блоком "опишите свои эмоции"-он без fieldset(

2022-01-26 20:17 UTC, DaryaNikolaeva31 commented on source/sass/blocks/form-group.scss
> +    margin-left: 279px;
стандартный?

2022-01-26 22:21 UTC, DaryaNikolaeva31 commented on source/sass/blocks/photo-card.scss
> +    left: 425px;
ограничила высоту картинки

2022-01-27 10:28 UTC, DaryaNikolaeva31 commented on source/sass/blocks/photo-card.scss
> +    opacity: 0.6;
я видимо не туда его добавила?ничего не поменялось(

2022-01-27 10:29 UTC, DaryaNikolaeva31 commented on source/sass/blocks/form-group.scss
> +}
заменила на field__description

2022-01-27 10:32 UTC, DaryaNikolaeva31 commented on source/sass/blocks/form-group.scss
> +    margin-left: 279px;
я убрала паддинги и марджины и добавила на филдсет бордер, но заголовки по центру не встали(
мне их все-таки подгонять паддингами?

2022-01-27 21:19 UTC, wrgraff commented on source/index.html
> +          <button class="arrow-switch__buttons arrow-switch__buttons--back">
Но это же элемент, который одна из них

2022-01-27 21:20 UTC, wrgraff commented on source/index.html
> +            <span class="visually-hidden">Смотреть отзыв №1</span>
С модификаторами все гуд

2022-01-27 21:21 UTC, wrgraff commented on source/sass/blocks/map-picture.scss
> +}
Высоту не убирай, это же айфрейм, он не знает сам по себе какой высоты показать

2022-01-27 21:29 UTC, wrgraff commented on source/sass/blocks/download.scss
> +    background-position: 208px 146px, 0 0;
Пока неправильно, написал тебе что как )

2022-01-27 21:29 UTC, wrgraff commented on source/sass/blocks/download.scss
> +    background-size: 660px 545px, 660px 729px;
Что-то не учла )

2022-01-27 21:30 UTC, wrgraff commented on source/sass/blocks/download.scss
> +    background-position: 0 184px, 0 0;
Чтобы под ней не было полосы, указывай просто позицию "в самом низу", то есть `bottom` или `100%`

2022-01-27 21:31 UTC, wrgraff commented on source/sass/blocks/arrow-switch.scss
> +}
`left` и/или `right` поместила в общий класс скорее всего

2022-01-27 21:32 UTC, wrgraff commented on source/sass/blocks/switch.scss
> +  box-shadow: 0 4px 4px rgba($black, 0.25);
Не верю!

2022-01-27 21:34 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +.form-group__heading--emotions {
На курсе проскочишь.
Напомню:
Некоторые отметки-смайлы (или их отсутствие) имеют определенный смысл:
- 🚀 — нарушение критерия или нерабочий код, который обязательно нужно поправить
- 🙁 — плохое решение, которое очень хотелось бы поправить
- без смайла — не очень критичное замечание
- 👍 — хвалю, ничего менять не нужно

2022-01-27 21:37 UTC, wrgraff commented on source/sass/blocks/photo-card.scss
> +    opacity: 0.6;
ОН работает. Но надо opacity то убрать.
И можно побольше поставить силу эффекта.

И еще надо ловить hover непосредственно на интерактивном элементе, то есть на ссылке. И через нее картинку внутри стилизовать

2022-01-27 21:38 UTC, wrgraff commented on source/sass/blocks/photo-card.scss
> +    left: 425px;
`1956px`??
По макету ограничить! По макету!

2022-01-27 21:39 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +}
А порядок элементов блока `.field` все равно идет через `.form-group__wrapper--contact .form-group__field`

2022-01-27 22:09 UTC, DaryaNikolaeva31 commented on source/sass/blocks/download.scss
> +    background-position: 208px 146px, 0 0;
ок, добавила cover

2022-01-27 22:11 UTC, DaryaNikolaeva31 commented on source/sass/blocks/download.scss
> +    background-position: 0 184px, 0 0;
ок
полосу вроде убрала уже

2022-01-27 22:12 UTC, DaryaNikolaeva31 commented on source/sass/blocks/arrow-switch.scss
> +}
да, невнимательность мое второе имя

2022-01-27 22:14 UTC, DaryaNikolaeva31 commented on source/sass/blocks/form-сheckbox.scss
исправили!

2022-01-27 22:18 UTC, DaryaNikolaeva31 commented on source/sass/blocks/photo-card.scss
> +    opacity: 0.6;
убрала opacity 
состояние hover перенесла на link
вообще этого в стайлгайде нет-это была моя инициатива
думала так нагляднее будет
но учитывая что я еще состояния не сделала-ждет меня и без того большая работа

2022-01-27 22:20 UTC, DaryaNikolaeva31 commented on source/sass/blocks/photo-card.scss
> +    left: 425px;
это меня стукнуло что-то
и откуда вообще я придумала это?)
исправила на 506px

2022-01-28 16:16 UTC, wrgraff commented on source/sass/blocks/photo-card.scss
> +    left: 425px;
Потом напомни разобрать с тобой `object-fit`

2022-01-28 16:17 UTC, merged